// Bulgarian locale strings + sample tournament data
// Current date context: May 17, 2026

const BG = {
  appName: "Билярд Турнири",
  months: ["Януари","Февруари","Март","Април","Май","Юни","Юли","Август","Септември","Октомври","Ноември","Декември"],
  monthsShort: ["Ян","Фев","Мар","Апр","Май","Юни","Юли","Авг","Сеп","Окт","Ное","Дек"],
  daysShort: ["Пн","Вт","Ср","Чт","Пт","Сб","Нд"],
  daysFull: ["Понеделник","Вторник","Сряда","Четвъртък","Петък","Събота","Неделя"],
  today: "Днес",
  calendar: "Календар",
  list: "Списък",
  tournaments: "турнира",
  tournament: "турнир",
  noTournaments: "Няма турнири",
  filters: "Филтри",
  apply: "Приложи",
  reset: "Изчисти",
  clearAll: "Изчисти всички",
  type: "Вид",
  level: "Ниво",
  pro: "Про",
  amateur: "Аматьор",
  both: "Смесен",
  all: "Всички",
  handicap: "Хандикап",
  yes: "Да",
  no: "Не",
  any: "Всеки",
  anyF: "Всяка",
  city: "Град",
  club: "Клуб",
  startHour: "Начален час",
  dressCode: "Дрескод",
  edit: "Редактирай",
  delete: "Изтрий",
  add: "Добави",
  addTournament: "Добави турнир",
  save: "Запази",
  cancel: "Отказ",
  login: "Вход",
  logout: "Изход",
  username: "Потребител",
  password: "Парола",
  admin: "Администратор",
  adminMode: "Админ режим",
  version: "Издание",
  name: "Име",
  search: "Търси",
  searchPlaceholder: "Търси по име или клуб…",
  weekends: "Уикенди",
  workdays: "Работни",
  newTournament: "Нов турнир",
  editTournament: "Редакция",
  past: "Минал",
  upcoming: "Предстоящ",
  ongoing: "Днес",
  details: "Детайли",
  back: "Назад",
  done: "Готово",
  deleteConfirm: "Изтриване на турнир?",
  deleteConfirmBody: "Това действие е необратимо.",
  loginTitle: "Вход за администратори",
  loginHint: "Само одобрени потребители могат да управляват турнирите.",
  ballType: { 8: "8-Бол", 9: "9-Бол", 10: "10-Бол" },
  filtersActive: "активни филтра",
  oneFilterActive: "активен филтър",
  results: "резултата",
  oneResult: "резултат",
};

// Sample tournaments — current date is May 17, 2026.
// We populate May–June 2026 with realistic Bulgarian billiards events.
const TOURNAMENTS = [
  { id: 1,  name: "Sofia Spring Open", version: "Q1",  type: 9,  level: "pro",     handicap: false, city: "София",        club: "Pool Pro Sofia",        date: "2026-05-02", startHour: "10:00", dressCode: true  },
  { id: 2,  name: "Тракия Купа",        version: "2",   type: 8,  level: "amateur", handicap: true,  city: "Пловдив",      club: "Билярд Тракия",         date: "2026-05-03", startHour: "14:00", dressCode: false },
  { id: 3,  name: "Морски Турнир",      version: "1",   type: 10, level: "pro",     handicap: false, city: "Варна",        club: "Морски Билярд",         date: "2026-05-05", startHour: "18:00", dressCode: true  },
  { id: 4,  name: "Парадайс Челендж",   version: "5",   type: 9,  level: "both",    handicap: true,  city: "София",        club: "Билярд Клуб Парадайс",  date: "2026-05-08", startHour: "19:00", dressCode: false },
  { id: 5,  name: "Дунав Купа",         version: "3",   type: 8,  level: "amateur", handicap: false, city: "Русе",         club: "Дунав Билярд",          date: "2026-05-09", startHour: "11:00", dressCode: false },
  { id: 6,  name: "Pool Black Open",    version: "Q2",  type: 10, level: "pro",     handicap: false, city: "Варна",        club: "Pool Black",            date: "2026-05-09", startHour: "16:00", dressCode: true  },
  { id: 7,  name: "Аматьорска Лига",    version: "4",   type: 9,  level: "amateur", handicap: true,  city: "Стара Загора", club: "Загора Пул",            date: "2026-05-10", startHour: "13:00", dressCode: false },
  { id: 8,  name: "Бургас Сън Сериес",  version: "1",   type: 8,  level: "both",    handicap: false, city: "Бургас",       club: "Бургас Пул Клуб",       date: "2026-05-14", startHour: "17:30", dressCode: false },
  { id: 9,  name: "Alex Билярд Купа",   version: "7",   type: 9,  level: "pro",     handicap: false, city: "София",        club: "Алекс Билярд",          date: "2026-05-16", startHour: "10:00", dressCode: true  },
  { id: 10, name: "Студентски Турнир",  version: "2",   type: 8,  level: "amateur", handicap: true,  city: "Велико Търново", club: "Търново Билярд",      date: "2026-05-16", startHour: "12:00", dressCode: false },
  { id: 11, name: "Пирин Купа",         version: "1",   type: 10, level: "both",    handicap: false, city: "Благоевград",  club: "Пирин Пул",             date: "2026-05-17", startHour: "15:00", dressCode: false },
  { id: 12, name: "Sofia Masters",      version: "Q2",  type: 9,  level: "pro",     handicap: false, city: "София",        club: "Pool Pro Sofia",        date: "2026-05-21", startHour: "18:00", dressCode: true  },
  { id: 13, name: "Плевен Опън",        version: "3",   type: 8,  level: "amateur", handicap: true,  city: "Плевен",       club: "Плевен Билярд",         date: "2026-05-23", startHour: "11:00", dressCode: false },
  { id: 14, name: "Pool Pro Седмичен",  version: "12",  type: 9,  level: "both",    handicap: false, city: "София",        club: "Pool Pro Sofia",        date: "2026-05-23", startHour: "19:00", dressCode: false },
  { id: 15, name: "Билярд Тракия Гран При", version: "2", type: 10, level: "pro",   handicap: false, city: "Пловдив",      club: "Билярд Тракия",         date: "2026-05-24", startHour: "13:00", dressCode: true  },
  { id: 16, name: "Морски Аматьори",    version: "5",   type: 8,  level: "amateur", handicap: true,  city: "Варна",        club: "Морски Билярд",         date: "2026-05-28", startHour: "18:30", dressCode: false },
  { id: 17, name: "Парадайс Найт",      version: "6",   type: 9,  level: "both",    handicap: false, city: "София",        club: "Билярд Клуб Парадайс",  date: "2026-05-30", startHour: "20:00", dressCode: true  },
  { id: 18, name: "Бургас Закрит",      version: "2",   type: 10, level: "pro",     handicap: false, city: "Бургас",       club: "Бургас Пул Клуб",       date: "2026-05-31", startHour: "14:00", dressCode: true  },
  { id: 19, name: "Pool Pro Sofia Open",version: "Q3",  type: 9,  level: "pro",     handicap: false, city: "София",        club: "Pool Pro Sofia",        date: "2026-06-04", startHour: "10:00", dressCode: true  },
  { id: 20, name: "Дунав Аматьорски",   version: "4",   type: 8,  level: "amateur", handicap: true,  city: "Русе",         club: "Дунав Билярд",          date: "2026-06-06", startHour: "12:00", dressCode: false },
  { id: 21, name: "Pool Black Серия",   version: "3",   type: 9,  level: "both",    handicap: false, city: "Варна",        club: "Pool Black",            date: "2026-06-06", startHour: "17:00", dressCode: false },
  { id: 22, name: "Загора Челендж",     version: "5",   type: 10, level: "pro",     handicap: false, city: "Стара Загора", club: "Загора Пул",            date: "2026-06-07", startHour: "15:00", dressCode: true  },
  { id: 23, name: "Алекс Месечен",      version: "8",   type: 8,  level: "amateur", handicap: true,  city: "София",        club: "Алекс Билярд",          date: "2026-06-13", startHour: "13:00", dressCode: false },
  { id: 24, name: "Пирин Аматьори",     version: "2",   type: 9,  level: "amateur", handicap: true,  city: "Благоевград",  club: "Пирин Пул",             date: "2026-06-14", startHour: "11:00", dressCode: false },
  { id: 25, name: "Sofia City Cup",     version: "1",   type: 10, level: "pro",     handicap: false, city: "София",        club: "Pool Pro Sofia",        date: "2026-06-19", startHour: "18:00", dressCode: true  },
  { id: 26, name: "Тракия Лятна Лига",  version: "1",   type: 9,  level: "both",    handicap: false, city: "Пловдив",      club: "Билярд Тракия",         date: "2026-06-20", startHour: "14:00", dressCode: false },
  { id: 27, name: "Парадайс Аматьори",  version: "7",   type: 8,  level: "amateur", handicap: true,  city: "София",        club: "Билярд Клуб Парадайс",  date: "2026-06-20", startHour: "16:00", dressCode: false },
  { id: 28, name: "Велико Опън",        version: "1",   type: 10, level: "both",    handicap: false, city: "Велико Търново", club: "Търново Билярд",      date: "2026-06-21", startHour: "13:00", dressCode: false },
  { id: 29, name: "Морски Финал",       version: "Q4",  type: 9,  level: "pro",     handicap: false, city: "Варна",        club: "Морски Билярд",         date: "2026-06-27", startHour: "19:00", dressCode: true  },
  { id: 30, name: "Sofia Закриване",    version: "F",   type: 10, level: "pro",     handicap: false, city: "София",        club: "Pool Pro Sofia",        date: "2026-06-28", startHour: "17:00", dressCode: true  },
];

const CITIES = ["София","Пловдив","Варна","Бургас","Русе","Стара Загора","Плевен","Велико Търново","Благоевград"];
const CLUBS = [
  "Pool Pro Sofia","Билярд Клуб Парадайс","Алекс Билярд",
  "Билярд Тракия","Пул Пловдив",
  "Морски Билярд","Pool Black",
  "Бургас Пул Клуб","Дунав Билярд","Загора Пул",
  "Плевен Билярд","Търново Билярд","Пирин Пул",
];

window.BG = BG;
window.TOURNAMENTS = TOURNAMENTS;
window.CITIES = CITIES;
window.CLUBS = CLUBS;
window.TODAY = new Date(2026, 4, 17); // May 17, 2026
