create type public.tournament_level as enum ('pro', 'amateur', 'both');

create table public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) > 0),
  version text not null check (length(trim(version)) > 0),
  type smallint not null check (type in (8, 9, 10)),
  level public.tournament_level not null,
  handicap boolean not null default false,
  city text not null check (length(trim(city)) > 0),
  club text not null check (length(trim(club)) > 0),
  date date not null,
  start_hour time not null,
  dress_code boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'admin' check (role in ('admin', 'owner')),
  invited_at timestamptz not null default now(),
  accepted_at timestamptz
);

create index tournaments_date_start_hour_idx on public.tournaments (date, start_hour);
create index tournaments_city_idx on public.tournaments (city);
create index tournaments_club_idx on public.tournaments (club);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger tournaments_touch_updated_at
before update on public.tournaments
for each row execute function public.touch_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles ap
    where ap.user_id = auth.uid()
  );
$$;

alter table public.tournaments enable row level security;
alter table public.admin_profiles enable row level security;

create policy "Anyone can read tournaments"
on public.tournaments
for select
using (true);

create policy "Admins can insert tournaments"
on public.tournaments
for insert
with check (public.is_admin());

create policy "Admins can update tournaments"
on public.tournaments
for update
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete tournaments"
on public.tournaments
for delete
using (public.is_admin());

create policy "Admins can read admin profiles"
on public.admin_profiles
for select
using (public.is_admin());

insert into public.tournaments
  (id, name, version, type, level, handicap, city, club, date, start_hour, dress_code)
values
  (1, 'Sofia Spring Open', 'Q1', 9, 'pro', false, 'София', 'Pool Pro Sofia', '2026-05-02', '10:00', true),
  (2, 'Тракия Купа', '2', 8, 'amateur', true, 'Пловдив', 'Билярд Тракия', '2026-05-03', '14:00', false),
  (3, 'Морски Турнир', '1', 10, 'pro', false, 'Варна', 'Морски Билярд', '2026-05-05', '18:00', true),
  (4, 'Парадайс Челендж', '5', 9, 'both', true, 'София', 'Билярд Клуб Парадайс', '2026-05-08', '19:00', false),
  (5, 'Дунав Купа', '3', 8, 'amateur', false, 'Русе', 'Дунав Билярд', '2026-05-09', '11:00', false),
  (6, 'Pool Black Open', 'Q2', 10, 'pro', false, 'Варна', 'Pool Black', '2026-05-09', '16:00', true),
  (7, 'Аматьорска Лига', '4', 9, 'amateur', true, 'Стара Загора', 'Загора Пул', '2026-05-10', '13:00', false),
  (8, 'Бургас Сън Сериес', '1', 8, 'both', false, 'Бургас', 'Бургас Пул Клуб', '2026-05-14', '17:30', false),
  (9, 'Alex Билярд Купа', '7', 9, 'pro', false, 'София', 'Алекс Билярд', '2026-05-16', '10:00', true),
  (10, 'Студентски Турнир', '2', 8, 'amateur', true, 'Велико Търново', 'Търново Билярд', '2026-05-16', '12:00', false),
  (11, 'Пирин Купа', '1', 10, 'both', false, 'Благоевград', 'Пирин Пул', '2026-05-17', '15:00', false),
  (12, 'Sofia Masters', 'Q2', 9, 'pro', false, 'София', 'Pool Pro Sofia', '2026-05-21', '18:00', true),
  (13, 'Плевен Опън', '3', 8, 'amateur', true, 'Плевен', 'Плевен Билярд', '2026-05-23', '11:00', false),
  (14, 'Pool Pro Седмичен', '12', 9, 'both', false, 'София', 'Pool Pro Sofia', '2026-05-23', '19:00', false),
  (15, 'Билярд Тракия Гран При', '2', 10, 'pro', false, 'Пловдив', 'Билярд Тракия', '2026-05-24', '13:00', true),
  (16, 'Морски Аматьори', '5', 8, 'amateur', true, 'Варна', 'Морски Билярд', '2026-05-28', '18:30', false),
  (17, 'Парадайс Найт', '6', 9, 'both', false, 'София', 'Билярд Клуб Парадайс', '2026-05-30', '20:00', true),
  (18, 'Бургас Закрит', '2', 10, 'pro', false, 'Бургас', 'Бургас Пул Клуб', '2026-05-31', '14:00', true),
  (19, 'Pool Pro Sofia Open', 'Q3', 9, 'pro', false, 'София', 'Pool Pro Sofia', '2026-06-04', '10:00', true),
  (20, 'Дунав Аматьорски', '4', 8, 'amateur', true, 'Русе', 'Дунав Билярд', '2026-06-06', '12:00', false),
  (21, 'Pool Black Серия', '3', 9, 'both', false, 'Варна', 'Pool Black', '2026-06-06', '17:00', false),
  (22, 'Загора Челендж', '5', 10, 'pro', false, 'Стара Загора', 'Загора Пул', '2026-06-07', '15:00', true),
  (23, 'Алекс Месечен', '8', 8, 'amateur', true, 'София', 'Алекс Билярд', '2026-06-13', '13:00', false),
  (24, 'Пирин Аматьори', '2', 9, 'amateur', true, 'Благоевград', 'Пирин Пул', '2026-06-14', '11:00', false),
  (25, 'Sofia City Cup', '1', 10, 'pro', false, 'София', 'Pool Pro Sofia', '2026-06-19', '18:00', true),
  (26, 'Тракия Лятна Лига', '1', 9, 'both', false, 'Пловдив', 'Билярд Тракия', '2026-06-20', '14:00', false),
  (27, 'Парадайс Аматьори', '7', 8, 'amateur', true, 'София', 'Билярд Клуб Парадайс', '2026-06-20', '16:00', false),
  (28, 'Велико Опън', '1', 10, 'both', false, 'Велико Търново', 'Търново Билярд', '2026-06-21', '13:00', false),
  (29, 'Морски Финал', 'Q4', 9, 'pro', false, 'Варна', 'Морски Билярд', '2026-06-27', '19:00', true),
  (30, 'Sofia Закриване', 'F', 10, 'pro', false, 'София', 'Pool Pro Sofia', '2026-06-28', '17:00', true);

select setval(pg_get_serial_sequence('public.tournaments', 'id'), 30, true);
